# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Python\PyQt\Project\my_dlib_face_detection_application\TrainShapePredictorParametersGui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TrainShapePredictorParametersDialog(object):
    def setupUi(self, TrainShapePredictorParametersDialog):
        TrainShapePredictorParametersDialog.setObjectName(_fromUtf8("TrainShapePredictorParametersDialog"))
        TrainShapePredictorParametersDialog.resize(707, 722)
        self.verticalLayout_13 = QtGui.QVBoxLayout(TrainShapePredictorParametersDialog)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_12.addWidget(self.label)
        self.line = QtGui.QFrame(TrainShapePredictorParametersDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_12.addWidget(self.line)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_12 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_2.addWidget(self.label_12)
        self.groupBox = QtGui.QGroupBox(TrainShapePredictorParametersDialog)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.line_10 = QtGui.QFrame(TrainShapePredictorParametersDialog)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.verticalLayout_2.addWidget(self.line_10)
        self.verticalLayout_12.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_13 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_4.addWidget(self.label_13)
        self.spinBox = QtGui.QSpinBox(TrainShapePredictorParametersDialog)
        self.spinBox.setMaximum(1000)
        self.spinBox.setProperty("value", 10)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_4.addWidget(self.spinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_12.addLayout(self.verticalLayout_3)
        self.line_2 = QtGui.QFrame(TrainShapePredictorParametersDialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_12.addWidget(self.line_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.label_14 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_5.addWidget(self.label_14)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(TrainShapePredictorParametersDialog)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.horizontalLayout_5.addWidget(self.doubleSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_12.addLayout(self.verticalLayout_4)
        self.line_3 = QtGui.QFrame(TrainShapePredictorParametersDialog)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_12.addWidget(self.line_3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_5 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.label_15 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_6.addWidget(self.label_15)
        self.spinBox_2 = QtGui.QSpinBox(TrainShapePredictorParametersDialog)
        self.spinBox_2.setMaximum(10000)
        self.spinBox_2.setSingleStep(100)
        self.spinBox_2.setProperty("value", 400)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.horizontalLayout_6.addWidget(self.spinBox_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_12.addLayout(self.verticalLayout_5)
        self.line_4 = QtGui.QFrame(TrainShapePredictorParametersDialog)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_12.addWidget(self.line_4)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_6 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.label_16 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_7.addWidget(self.label_16)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(TrainShapePredictorParametersDialog)
        self.doubleSpinBox_2.setSingleStep(0.1)
        self.doubleSpinBox_2.setProperty("value", 0.1)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_12.addLayout(self.verticalLayout_6)
        self.line_5 = QtGui.QFrame(TrainShapePredictorParametersDialog)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_12.addWidget(self.line_5)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_7 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_7.addWidget(self.label_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.label_17 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_8.addWidget(self.label_17)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(TrainShapePredictorParametersDialog)
        self.doubleSpinBox_3.setSingleStep(0.1)
        self.doubleSpinBox_3.setProperty("value", 0.1)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.verticalLayout_12.addLayout(self.verticalLayout_7)
        self.line_6 = QtGui.QFrame(TrainShapePredictorParametersDialog)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_12.addWidget(self.line_6)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_8 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_8.addWidget(self.label_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.label_18 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_9.addWidget(self.label_18)
        self.spinBox_3 = QtGui.QSpinBox(TrainShapePredictorParametersDialog)
        self.spinBox_3.setMaximum(1000)
        self.spinBox_3.setProperty("value", 20)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.horizontalLayout_9.addWidget(self.spinBox_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.verticalLayout_12.addLayout(self.verticalLayout_8)
        self.line_7 = QtGui.QFrame(TrainShapePredictorParametersDialog)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_12.addWidget(self.line_7)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_9 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_9.addWidget(self.label_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.label_19 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_10.addWidget(self.label_19)
        self.spinBox_4 = QtGui.QSpinBox(TrainShapePredictorParametersDialog)
        self.spinBox_4.setMaximum(10000)
        self.spinBox_4.setSingleStep(100)
        self.spinBox_4.setProperty("value", 500)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.horizontalLayout_10.addWidget(self.spinBox_4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.verticalLayout_12.addLayout(self.verticalLayout_9)
        self.line_8 = QtGui.QFrame(TrainShapePredictorParametersDialog)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_12.addWidget(self.line_8)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_10 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_10.addWidget(self.label_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.label_20 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_11.addWidget(self.label_20)
        self.spinBox_5 = QtGui.QSpinBox(TrainShapePredictorParametersDialog)
        self.spinBox_5.setMaximum(1000)
        self.spinBox_5.setProperty("value", 20)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.horizontalLayout_11.addWidget(self.spinBox_5)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.line_9 = QtGui.QFrame(TrainShapePredictorParametersDialog)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.verticalLayout_12.addWidget(self.line_9)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_11 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_11.addWidget(self.label_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.label_21 = QtGui.QLabel(TrainShapePredictorParametersDialog)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_12.addWidget(self.label_21)
        self.spinBox_6 = QtGui.QSpinBox(TrainShapePredictorParametersDialog)
        self.spinBox_6.setMaximum(1000)
        self.spinBox_6.setProperty("value", 4)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.horizontalLayout_12.addWidget(self.spinBox_6)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)

        self.retranslateUi(TrainShapePredictorParametersDialog)
        QtCore.QMetaObject.connectSlotsByName(TrainShapePredictorParametersDialog)

    def retranslateUi(self, TrainShapePredictorParametersDialog):
        TrainShapePredictorParametersDialog.setWindowTitle(_translate("TrainShapePredictorParametersDialog", "人脸特征点训练参数设置", None))
        self.label.setText(_translate("TrainShapePredictorParametersDialog", "人脸特征点检测器训练参数说明：", None))
        self.label_2.setText(_translate("TrainShapePredictorParametersDialog", "be_verbose：如果值为True，则会在控制台中打印出过程信息。", None))
        self.label_12.setText(_translate("TrainShapePredictorParametersDialog", "be_verbose", None))
        self.radioButton.setText(_translate("TrainShapePredictorParametersDialog", "True", None))
        self.radioButton_2.setText(_translate("TrainShapePredictorParametersDialog", "False", None))
        self.label_3.setText(_translate("TrainShapePredictorParametersDialog", "cascade_depth：训练模型所用cascades的层数。", None))
        self.label_13.setText(_translate("TrainShapePredictorParametersDialog", "cascade_depth", None))
        self.label_4.setText(_translate("TrainShapePredictorParametersDialog", "feature_pool_region_padding：采样特征池的区域大小，比如一个0.5的padding就会导致\n"
"算法使用一个2*2的方框来对像素点采样。", None))
        self.label_14.setText(_translate("TrainShapePredictorParametersDialog", "feature_pool_region_padding", None))
        self.label_5.setText(_translate("TrainShapePredictorParametersDialog", "feature_pool_size:用来从随机树中生成特征的像素数量。", None))
        self.label_15.setText(_translate("TrainShapePredictorParametersDialog", "feature_pool_size", None))
        self.label_6.setText(_translate("TrainShapePredictorParametersDialog", "lambda_param：控制特征采样要有多紧密。这个值越小采集的特征越近，因为采集的像素点距离更小。", None))
        self.label_16.setText(_translate("TrainShapePredictorParametersDialog", "lambda_param", None))
        self.label_7.setText(_translate("TrainShapePredictorParametersDialog", "nu：正则化参数。这个值越大，算法对数据的拟合程度越高，但有过拟合的风险。取值范围是0到1。", None))
        self.label_17.setText(_translate("TrainShapePredictorParametersDialog", "nu", None))
        self.label_8.setText(_translate("TrainShapePredictorParametersDialog", "num_test_splits：每个节点分离出的特征个数。最后只会选择能最好地分割特征的那个节点。", None))
        self.label_18.setText(_translate("TrainShapePredictorParametersDialog", "num_test_splits", None))
        self.label_9.setText(_translate("TrainShapePredictorParametersDialog", "num_trees_per_cascade_level：每个cascade中树的个数。", None))
        self.label_19.setText(_translate("TrainShapePredictorParametersDialog", "num_trees_per_cascade_level", None))
        self.label_10.setText(_translate("TrainShapePredictorParametersDialog", "oversampling_amount：每个训练样本中随机选取的初始采样点的数目。", None))
        self.label_20.setText(_translate("TrainShapePredictorParametersDialog", "oversampling_amount", None))
        self.label_11.setText(_translate("TrainShapePredictorParametersDialog", "tree_depth：每个cascade中树的深度。每颗树中有pow(2, get_tree_depth())个叶子节点。", None))
        self.label_21.setText(_translate("TrainShapePredictorParametersDialog", "tree_depth", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TrainShapePredictorParametersDialog = QtGui.QDialog()
    ui = Ui_TrainShapePredictorParametersDialog()
    ui.setupUi(TrainShapePredictorParametersDialog)
    TrainShapePredictorParametersDialog.show()
    sys.exit(app.exec_())

